Petugas first design complete
Khip01/si_koperasi_mahasiswa pull request #5
Opened 2024-05-05 13:17 UTC by Raruu

# Complete
### Click 1x form petugas
### Scroll form isian
 <img src="https://media1.tenor.com/m/_WvRwAlhge8AAAAC/bocchi-the-rock-kita-ikuyo.gif"/>
- Raruu

2024-05-05 18:31 UTC, Khip01 requested changes
# ⚙️Request to Change
Change request for **Petugas** page 

- [ Tabel Daftar Barang ] *tabel bagian kiri
  - Untuk tabel daftar barang query nya tambahin kondisi,
  ```sql 
  WHERE kode_transaksi_pembeli NOT NULL AND kode_transaksi_supplier IS NULL 
   ```
  - Judul nya diganti Daftar Pesanan Pembeli
  - Tabel nya gausa dikasih interaksi, jadi cuman nampilin doang

- [Tabel Daftar Transaksi Supplier] *tabel bagian kanan
  - Nampilin Daftar Semua Transaksi Pembeli. Jadi yang ditampilin tabel ```transaksi_pembeli```

- [Tabel Daftar Pesanan] *tabel yang di pop up
  - Mending tabel itu dibuat milih kita sebagai petugas yang mana, jadi yang ditampilin daftar data di tabel ```petugas```
  - Mekaniknya, kita sebagai user milih pada saat ini bertugas sebagai petugas dengan identitas yang mana, jadi row nya dipencet, trus button add nya buat nyimpen data ```kode_petugas``` yang kita piih tadi...


You can do self improvement as long as you understand the basic mechanics of the web ok😉

Cheer up!🔥  ~khip

2024-05-05 23:40 UTC, Raruu commented
> * [ Tabel Daftar Barang ] *tabel bagian kiri
>   
>   * Untuk tabel daftar barang query nya tambahin kondisi,
>   
>   ```sql
>   WHERE kode_transaksi_pembeli NOT NULL AND kode_transaksi_supplier IS NULL 
>   ```

` WHERE kode_transaksi_pembeli IS NOT NULL AND kode_transaksi_supplier IS NULL  `
Jadi kosong dong?

2024-05-06 00:40 UTC, Khip01 commented
> > * [ Tabel Daftar Barang ] *tabel bagian kiri
> >   
> >   * Untuk tabel daftar barang query nya tambahin kondisi,
> >   
> >   ```sql
> >   WHERE kode_transaksi_pembeli NOT NULL AND kode_transaksi_supplier IS NULL 
> >   ```
> 
> `WHERE kode_transaksi_pembeli IS NOT NULL AND kode_transaksi_supplier IS NULL ` Jadi kosong dong?

Betul..

2024-05-06 03:45 UTC, Khip01 approved these changes
K then, we can move on 🎉
GG @Raruu 🎃

2024-05-06 03:45 UTC, merged